spring.application.name=ticketing

spring.datasource.url=jdbc:postgresql://ep-small-dew-a92gm2n6-pooler.gwc.azure.neon.tech/neondb
spring.datasource.password=${TICKETING-DB-PASS}
spring.datasource.username=${TICKETING-DB-USER}
spring.jpa.hibernate.ddl-auto=create-drop

server.servlet.context-path=/api/v1

