spring.application.name=ticketing

spring.datasource.url=${TICKETING_DB_URL}
spring.datasource.password=${TICKETING_DB_PASS}
spring.datasource.username=${TICKETING_DB_USER}
spring.jpa.hibernate.ddl-auto=create-drop

server.servlet.context-path=/api-v1

logging.level.org.springframework.security=DEBUG